### PR TITLE
New Features and new Demo

### PR DESCRIPTION
**Pull request by dacastro4**
The only two changes were the missing "return" on the iconHover function and I changed ng-mouseenter by ng-mouseover because it wasn't working at all.

### CODE REVIEW

**Comment by melloc01** [comment]
Weird. Mouseenter works for me @dacastro4, can you clone and try again on the index.html file?
Perhaps you had some element blocking the mouseenter event. (just a guess)

**Comment by dacastro4** [comment]
@melloc01 You're absolutely right. It is working on the demo but I'm 100% sure that nothing is blocking the event. It's weird I already tested with nothing but the stars and it's not working.

**Comment by melloc01** [comment]
Humm.. does it get solved by the _mouseover_ event? since they behave differently, there's a chance it'll work on scenarios where _mouseenter_ does not

**Comment by melloc01** [comment]
If **mouseover** realy helps I think I'll just update on my branch, your branch is conflicting =\

Please solve the conflicts, close (and I'll change) or create a new PR with no conflcits.

thanks again @dacastro4  = ]]

**Comment by dacastro4** [comment]
@melloc01 I already resolved the conflicts.
No problem. That's why we are here.

**Comment by melloc01** [comment]
sweet @dacastro4, I like all of them. Will try them tonight =) gj :+1:

**Comment by dacastro4** [comment]
Hey @melloc01  I haven't heard anything yet. Did you tested it?

**Comment by melloc01** [comment]
long night, huh? guess something got in the way

**Pull request closed without merging**
