### PR TITLE
Added onStarClick attribute

### PR DESCRIPTION
**Pull request by whitef0x0**
Added attribute that allows you to add a post-click trigger function for star clicks.

### CODE REVIEW

**Comment by whitef0x0** [comment]
@melloc01 do you know when you'll be able to review this?

**Comment by melloc01** [comment]
hey @whitef0x0 
I cloned it yesterday's night, will take a look tonight :+1:!  Thanks in advance

**Comment by whitef0x0** [comment]
Any update on this @melloc01

**Comment by melloc01** [comment]
hey @whitef0x0, good idea having an "onStarClick", thanks for it =) 

I have a question:
Why `$rootScope` instead of `$scope`?

If we have it on `$scope` and want to assign to a `$rootScope function` it is easy, but the opposite way (like it is right now) it is not even possible, if I am not wrong.

``` javascript
...
$scope.myOnStarHandler = $rootScope.myHandlerFunc;
...
```

**Comment by whitef0x0** [comment]
Yea you are correct. I've changed it to $scope.

**Comment by melloc01** [comment]
cool @whitef0x0, saw your changes.

I tested but there was some issues with the comparison and I'd prefer to keep it simple so, what do you think in going like this? I tested and works very smoothly:

Inside the setValue function:

``` javascript
    ...
    // Execute custom trigger function if there is one
    if(attrs.onStarClick){
        scope.$eval(attrs.onStarClick);
    }
    ...
```

**Comment by whitef0x0** [comment]
yea that seems to be better

**Comment by whitef0x0** [comment]
Ok I updated my branch.

**Comment by whitef0x0** [comment]
@melloc01 does this work for you?

**Comment by whitef0x0** [comment]
@melloc01 ?

**Comment by melloc01** [comment]
@whitef0x0 seems you polluted this PR with another functionality. I'd have merged it long ago if it was not =) I'll take the files and update whatis related to  "added onStarClick"

**Comment by whitef0x0** [comment]
hmm okok. I'll make a separate PR for my other feature?

**Comment by melloc01** [comment]
@whitef0x0 yes, please

**Pull request closed without merging**
